<hr>
<P>
<H2>GET PBL:</H2>
<ul>
<li>See the PBL <a href="../doc/">documentation</a>.
<li>PBL is hosted on <a href="https://github.com/peterGraf/pbl">GitHub</a>. 
<li>Download the PBL master from <a href="https://github.com/peterGraf/pbl/archive/master.zip">GitHub</a>.
<li>Take a look at the PBL <a href="https://github.com/peterGraf/pbl/tree/master/src/src/">sources</a>.
<P>
<li>Take a look at <a href="http://spamprobe.sourceforge.net/">Spam Probe</a>, a project that uses PBL.
<li>PBL is listed as <a href="https://notabug.org/koz.ross/awesome-c#frameworks">awesome-c</a> framework.
</ul>
</DL>
<hr>
Copyright(C) 2003 - 2015 <a href="http://www.mission-base.com/peter/">Peter Graf</a>,
this software is distributed under the
<a href="https://opensource.org/licenses/MIT"
name="TOCMIT" target="new">MIT License</a>.

